AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'
    - 'config//**/*'
    - 'db/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/BlockLength:
  Exclude:
    - 'db/**/*'
