AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/users/passwords_controller.rb'
    - 'app/controllers/users/registrations_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'app/models/user.rb'
    - 'config/application.rb'
    - 'db/migrate/20230828142736_devise_create_users.rb'
    - 'db/migrate/20230828173344_add_old_passwords_table.rb'
